name: Railway 服務狀態監控

on:
  schedule:
    # 每小時檢查一次服務狀態
    - cron: '0 * * * *'
  workflow_dispatch: # 允許手動觸發

jobs:
  check-service:
    runs-on: ubuntu-latest
    steps:
      - name: 安裝 Railway CLI
        run: npm i -g @railway/cli

      - name: 檢查服務狀態
        id: check-status
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          SERVICE_ID: ${{ secrets.SERVICE_ID }}
        run: |
          # 獲取當前 UTC 時間
          HOUR=$(date -u +%H)
          
          # 檢查是否在工作時間內 (7-0 UTC)
          if [ $HOUR -ge 7 ] || [ $HOUR -lt 1 ]; then
            echo "處於工作時間，檢查服務狀態..."
            
            # 檢查服務是否正在運行
            STATUS=$(railway service status $SERVICE_ID | grep -i "status")
            
            if [[ $STATUS != *"UP"* ]]; then
              echo "服務未運行，正在重新啟動..."
              railway service restart $SERVICE_ID
              echo "已發送服務重啟請求"
            else
              echo "服務運行正常"
            fi
          else
            echo "處於非工作時間 (UTC 1-7)，不檢查服務狀態"
          fi 